# This is a program that prompt the user for hours(xh) and rate per hour (rph)
# by using input to compute grosspay(Pay)
xh = input("ENter Hours: ")
xr = input("ENter Rate: ")
xp = float(xh) * float(xr)
print("Pay:",xp)
